const Data = {
  productItems: [
    {
      id: 1,
      discount: 50,
      cover: "./images/flash/flash-1.png",
      images: [
        "./images/flash/flash-1.png",
        "./images/flash/flash-2.png",
        "./images/flash/flash-3.png",
        "./images/flash/flash-4.png",
      ],
      name: "Shoes",
      price: 100,
      gender: "Men",
    },
    {
      id: 2,
      discount: 40,
      cover: "./images/flash/flash-2.png",
      images: [
        "./images/flash/flash-2.png",
        "./images/flash/flash-1.png",
        "./images/flash/flash-3.png",
        "./images/flash/flash-4.png",
      ],
      name: "Watch",
      price: 20,
      gender: "Men",
    },
    {
      id: 3,
      discount: 40,
      cover: "./images/flash/flash-3.png",
      images: [
        "./images/flash/flash-3.png",
        "./images/flash/flash-1.png",
        "./images/flash/flash-2.png",
        "./images/flash/flash-4.png",
      ],
      name: "Smart Mobile Black",
      price: 200,
      gender: "Women",
    },
    {
      id: 4,
      discount: 40,
      cover: "./images/flash/flash-4.png",
      images: [
        "./images/flash/flash-4.png",
        "./images/flash/flash-3.png",
        "./images/flash/flash-1.png",
        "./images/flash/flash-2.png",
      ],
      name: "Smart Watch Black",
      price: 50,
      gender: "Women",
    },
    {
      id: 5,
      discount: 50,
      cover: "./images/flash/flash-1.png",
      images: [
        "./images/flash/flash-1.png",
        "./images/flash/flash-2.png",
        "./images/flash/flash-3.png",
        "./images/flash/flash-4.png",
      ],
      name: "Shoes",
      price: 100,
      gender: "Men",
    },
    {
      id: 6,
      discount: 50,
      cover: "./images/flash/flash-3.png",
      images: [
        "./images/flash/flash-3.png",
        "./images/flash/flash-1.png",
        "./images/flash/flash-2.png",
        "./images/flash/flash-4.png",
      ],
      name: "Shoes",
      price: 100,
      gender: "Women",
    },
  ],
};
export default Data;
